export const countries = [
  { code: "NL", name: "Nederland", flag: "🇳🇱" },
  { code: "BE", name: "België", flag: "🇧🇪" },
  { code: "DE", name: "Duitsland", flag: "🇩🇪" },
  { code: "FR", name: "Frankrijk", flag: "🇫🇷" },
  { code: "GB", name: "Verenigd Koninkrijk", flag: "🇬🇧" },
  { code: "IT", name: "Italië", flag: "🇮🇹" },
  { code: "ES", name: "Spanje", flag: "🇪🇸" },
  { code: "PT", name: "Portugal", flag: "🇵🇹" },
  { code: "PL", name: "Polen", flag: "🇵🇱" },
  { code: "SE", name: "Zweden", flag: "🇸🇪" },
  { code: "NO", name: "Noorwegen", flag: "🇳🇴" },
  { code: "DK", name: "Denemarken", flag: "🇩🇰" },
  { code: "FI", name: "Finland", flag: "🇫🇮" },
  { code: "AT", name: "Oostenrijk", flag: "🇦🇹" },
  { code: "CH", name: "Zwitserland", flag: "🇨🇭" },
  { code: "IE", name: "Ierland", flag: "🇮🇪" },
  { code: "LU", name: "Luxemburg", flag: "🇱🇺" },
  { code: "GR", name: "Griekenland", flag: "🇬🇷" },
  { code: "CZ", name: "Tsjechië", flag: "🇨🇿" },
  { code: "HU", name: "Hongarije", flag: "🇭🇺" },
  { code: "RO", name: "Roemenië", flag: "🇷🇴" },
  { code: "BG", name: "Bulgarije", flag: "🇧🇬" },
  { code: "HR", name: "Kroatië", flag: "🇭🇷" },
  { code: "US", name: "Verenigde Staten", flag: "🇺🇸" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "AU", name: "Australië", flag: "🇦🇺" },
  { code: "NZ", name: "Nieuw-Zeeland", flag: "🇳🇿" },
  { code: "BR", name: "Brazilië", flag: "🇧🇷" },
  { code: "MX", name: "Mexico", flag: "🇲🇽" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "CN", name: "China", flag: "🇨🇳" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "ZA", name: "Zuid-Afrika", flag: "🇿🇦" },
  { code: "TH", name: "Thailand", flag: "🇹🇭" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "PE", name: "Peru", flag: "🇵🇪" },
];
